---
# Source: fritzbox-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ke-fritzbox-exporter
  labels:
    helm.sh/chart: fritzbox-exporter-0.1.0
    app.kubernetes.io/name: fritzbox-exporter
    app.kubernetes.io/instance: ke
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
